# Generated by Django 2.2.1 on 2019-05-17 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='grade',
        ),
    ]
