# Generated by Django 2.2.1 on 2019-05-19 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_remove_students_grade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='Age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='Surname',
            new_name='surname',
        ),
        migrations.AddField(
            model_name='exams',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
