# Generated by Django 2.2.1 on 2019-05-19 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_auto_20190519_1210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='student',
            new_name='student_id',
        ),
    ]
