# Generated by Django 2.2.1 on 2019-05-20 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_exams_owners'),
    ]

    operations = [
        migrations.AddField(
            model_name='exams',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.Exams_owners'),
        ),
    ]
